version: '3.9'

services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: db
      MB_DB_PORT: 5431
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_DBNAME: metabase_db
    volumes:
      - ./metabase-data:/metabase-data # Persistent storage for Metabase data
    depends_on:
      - db
    networks:
      - postgres-network
  db:
    image: postgres:14 # Or another database image like mysql
    ports:
      - 5431:5431
    environment:
      POSTGRES_DB: metabase_db
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Persistent storage for PostgreSQL data
    command: -p 5431
    networks:
      - postgres-network
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=bootcamp_db
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - postgres-network
    container_name: postgres
  # jupyter:
  #   build:
  #     context: .
  #     dockerfile: ./docker/jupyter/Dockerfile
  #   volumes:
  #     - ./work:/home/jovyan/work
  #     - ./notebooks:/home/jovyan/notebooks
  #   ports:
  #     - 8888:8888
  #   command: "start-notebook.sh --NotebookApp.token="
  #   container_name: jupyter_notebook

volumes:
  database-data:

networks:
  postgres-network:
    driver: bridge