version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=bootcamp_db
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - postgres-network
    container_name: postgres
  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      - ./notebooks:/home/jovyan/notebooks
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
    container_name: jupyter_notebook

volumes:
  database-data:

networks:
  postgres-network:
    driver: bridge